
export const DEFAULT_ACTION = 'app/ManagerNews/DEFAULT_ACTION';
export const ADD_CATE_NEWS_ACTION = 'app/ManagerNews/ADD_CATE_NEWS_ACTION';
export const ADD_CATE_NEWS_ACTION_SUCCESS = 'app/ManagerNews/ADD_CATE_NEWS_ACTION_SUCCESS';
export const DEL_CATE_NEWS_ACTION = 'app/ManagerNews/DEL_CATE_NEWS_ACTION';
export const DEL_CATE_NEWS_ACTION_SUCCESS = 'app/ManagerNews/DEL_CATE_NEWS_ACTION_SUCCESS';
export const EDIT_CATE_NEWS_ACTION = 'app/ManagerNews/EDIT_CATE_NEWS_ACTION';
export const EDIT_CATE_NEWS_ACTION_SUCCESS = 'app/ManagerNews/EDIT_CATE_NEWS_ACTION_SUCCESS';
export const GET_LIST_CATE_NEWS_ACTION = 'app/ManagerNews/GET_LIST_CATE_NEWS_ACTION';
export const GET_LIST_CATE_NEWS_ACTION_SUCCESS = 'app/ManagerNews/GET_LIST_CATE_NEWS_ACTION_SUCCESS';
